// Single source of truth for the flower-shop demos.
// EDIT THIS FILE to change a demo: primary (white) + secondary (accent line) +
// accent palette index (0-11). Then commit & push — GitHub Pages redeploys; no
// Bela rebuild needed (the name/colour are passed to the demo at runtime).
//   palettes: 0 rose 1 peach 2 coral 3 gold 4 lavender 5 lilac 6 wine
//             7 terracotta 8 blush 9 dusty-blue 10 sage 11 mauve
export interface DemoShop { slug: string; name: string; primary: string; secondary: string; accent: number; }
export const DEMO_SHOPS: DemoShop[] = [
  { slug: "lulebore-flowers", name: "Luleborë Flowers", primary: "Luleborë", secondary: "Flowers", accent: 1 },
  { slug: "dyqan-lulesh-sara-flowers-and-gifts-shop", name: "Dyqan lulesh Sara Flowers & Gifts Shop", primary: "Sara", secondary: "Flowers & Gifts Shop", accent: 1 },
  { slug: "don-paulo-flowers", name: "Don Paulo Flowers", primary: "Don Paulo", secondary: "Flowers", accent: 8 },
  { slug: "bota-e-luleve", name: "BOTA E LULEVE", primary: "BOTA E LULEVE", secondary: "", accent: 8 },
  { slug: "dyqan-lulesh-shytis-flower", name: "Dyqan Lulesh Shyti's Flower", primary: "Shyti's", secondary: "Flower", accent: 8 },
  { slug: "golden-flowers", name: "Golden Flowers", primary: "Golden", secondary: "Flowers", accent: 3 },
  { slug: "handmade-ola", name: "Handmade Ola", primary: "Handmade Ola", secondary: "", accent: 3 },
  { slug: "house-of-flowers-lori", name: "House of Flowers Lori", primary: "House of Flowers Lori", secondary: "", accent: 8 },
  { slug: "flower-boutique", name: "Flower boutique", primary: "Flower", secondary: "boutique", accent: 2 },
  { slug: "tirana-flowers", name: "Tirana Flowers", primary: "Tirana", secondary: "Flowers", accent: 6 },
  { slug: "bloom-flower-exclusive", name: "Bloom Flower Exclusive", primary: "Bloom Flower Exclusive", secondary: "", accent: 8 },
  { slug: "hanaflower-al", name: "Hana Flower", primary: "Hana", secondary: "Flower", accent: 5 },
  { slug: "speaking-roses-albania", name: "Speaking Roses Albania", primary: "Speaking Roses", secondary: "Albania", accent: 0 },
  { slug: "joal-flowers", name: "JOAL Flowers", primary: "JOAL", secondary: "Flowers", accent: 3 },
  { slug: "wow-flowers", name: "WoW Flowers", primary: "WoW", secondary: "Flowers", accent: 2 },
  { slug: "floramour", name: "Floramour", primary: "Floramour", secondary: "", accent: 11 },
  { slug: "blumenhaus-flower-shop", name: "Blumenhaus Flower Shop", primary: "Blumenhaus", secondary: "Flower Shop", accent: 8 },
  { slug: "friends-of-flowers", name: "FRIENDS OF FLOWERS", primary: "FRIENDS OF", secondary: "FLOWERS", accent: 6 },
  { slug: "flowers-shop-angel", name: "Flowers shop Angel", primary: "Angel", secondary: "Flowers shop", accent: 3 },
  { slug: "belfiore", name: "Belfiore", primary: "Belfiore", secondary: "", accent: 2 },
  { slug: "fiore-tirana", name: "Fiore Tirana", primary: "Fiore", secondary: "Tirana", accent: 9 },
  { slug: "castle-of-flower", name: "Castle Of Flower", primary: "Castle Of", secondary: "Flower", accent: 0 },
  { slug: "anabela-flowers", name: "Anabela Flowers", primary: "Anabela", secondary: "Flowers", accent: 7 },
  { slug: "igiflower", name: "IgiFlower", primary: "IgiFlower", secondary: "", accent: 6 },
  { slug: "new-tirana-flowers", name: "New Tirana Flowers", primary: "New", secondary: "Tirana Flowers", accent: 3 },
  { slug: "eart-flowers-and-gifts", name: "Eart Flowers & Gifts", primary: "Eart", secondary: "Flowers & Gifts", accent: 7 },
  { slug: "flowers-elixir-store", name: "Flowers Elixir Store", primary: "Elixir", secondary: "Store", accent: 8 },
  { slug: "lujon-flowers", name: "Lujon Flowers", primary: "Lujon", secondary: "Flowers", accent: 7 },
  { slug: "d-ive-flowers-and-events", name: "D’IVE FLOWERS & EVENTS", primary: "D’IVE FLOWERS & EVENTS", secondary: "", accent: 2 },
  { slug: "smell-time-myslym-shyri", name: "Smell Time Myslym Shyri", primary: "Smell Time Myslym Shyri", secondary: "", accent: 5 },
  { slug: "artflower", name: "Artflower", primary: "Artflower", secondary: "", accent: 6 },
  { slug: "flowers-and-plants-ds", name: "Flowers and Plants DS", primary: "Plants DS", secondary: "Flowers and", accent: 10 },
  { slug: "le-rose-flowers-shop", name: "Le Rose flowers shop", primary: "Le Rose", secondary: "flowers shop", accent: 0 },
  { slug: "fleur-de-mel", name: "Fleur de Mel", primary: "Fleur de Mel", secondary: "", accent: 9 },
  { slug: "lotus-flowers-tirane", name: "Lotus Flowers Tiranë", primary: "Lotus", secondary: "Flowers Tiranë", accent: 8 },
  { slug: "silvi-flowers-tirane", name: "Silvi Flowers Tirane", primary: "Silvi", secondary: "Flowers Tirane", accent: 4 },
  { slug: "family-flowers", name: "Family Flowers", primary: "Family", secondary: "Flowers", accent: 11 },
  { slug: "florum", name: "FLORUM", primary: "FLORUM", secondary: "", accent: 1 },
  { slug: "mado-flowers-tirane", name: "Mado Flowers Tirane", primary: "Mado", secondary: "Flowers Tirane", accent: 10 },
  { slug: "bloem-flower-boutique-tirana", name: "Bloem Flower Boutique Tirana", primary: "Bloem", secondary: "Flower Boutique Tirana", accent: 8 },
  { slug: "flowers-by-des", name: "Flowers by Des", primary: "by Des", secondary: "Flowers", accent: 1 },
  { slug: "charm-flowers-shop", name: "CHARM FLOWERS SHOP", primary: "CHARM", secondary: "FLOWERS SHOP", accent: 5 },
  { slug: "lunariaa-eu-flower-cafe", name: "Lunariaa.eu Flower Café", primary: "Lunariaa.eu Flower Café", secondary: "", accent: 4 },
  { slug: "oazi-festiv", name: "Oazi Festiv", primary: "Oazi Festiv", secondary: "", accent: 9 },
  { slug: "tulip-touch-flower-shop-in-tirana", name: "Tulip Touch Flower Shop in Tirana", primary: "Tulip Touch Flower Shop in", secondary: "Tirana", accent: 1 },
  { slug: "tirana-colour-wine", name: "Tirana Colour Wine", primary: "Colour Wine", secondary: "Tirana", accent: 6 },
  { slug: "floral-fantasy", name: "Floral Fantasy", primary: "Floral Fantasy", secondary: "", accent: 5 },
  { slug: "dandelion-flower-tirana", name: "Dandelion Flower Tirana", primary: "Dandelion", secondary: "Flower Tirana", accent: 10 },
  { slug: "frida-xhoi-and-xhei", name: "Frida Xhoi & Xhei", primary: "Frida Xhoi & Xhei", secondary: "", accent: 2 },
  { slug: "artifiko-gift-shop", name: "Artifiko Gift Shop", primary: "Artifiko", secondary: "Gift Shop", accent: 7 },
  { slug: "the-tea-room", name: "The Tea Room", primary: "The Tea Room", secondary: "", accent: 4 },
  { slug: "geraldina-sposa", name: "Geraldina Sposa", primary: "Geraldina Sposa", secondary: "", accent: 10 },
  { slug: "dhurata-com", name: "Dhurata.com", primary: "Dhurata.com", secondary: "", accent: 5 },
  { slug: "maison-damour-flowers", name: "Maison D'amour Flowers", primary: "Maison D'amour", secondary: "Flowers", accent: 3 },
  { slug: "moon-decor-and-flowers", name: "Moon Decor & Flowers", primary: "Moon Decor", secondary: "& Flowers", accent: 2 },
  { slug: "bloom-flowers", name: "Bloom Flowers", primary: "Bloom", secondary: "Flowers", accent: 8 },
  { slug: "roses-flowers", name: "Roses flowers", primary: "Roses", secondary: "flowers", accent: 0 },
  { slug: "daisy-flower", name: "Daisy flower", primary: "Daisy", secondary: "flower", accent: 6 },
  { slug: "flowers-and-fragrance", name: "Flowers and Fragrance", primary: "Fragrance", secondary: "Flowers and", accent: 4 },
  { slug: "sara-flowers-shop", name: "Sara Flowers Shop", primary: "Sara", secondary: "Flowers Shop", accent: 3 },
  { slug: "flawless-flower-shop", name: "Flawless Flower Shop", primary: "Flawless", secondary: "Flower Shop", accent: 4 },
  { slug: "flower-shop-and-gifts", name: "Flower Shop & Gifts", primary: "Flower", secondary: "Shop & Gifts", accent: 4 },
  { slug: "paper-flower-tirana", name: "Paper Flower Tirana", primary: "Paper", secondary: "Flower Tirana", accent: 0 },
  { slug: "daci-flower", name: "Daçi Flower", primary: "Daçi", secondary: "Flower", accent: 1 },
  { slug: "naco-flower", name: "Naço flower", primary: "Naço", secondary: "flower", accent: 5 },
];
export const DEMO_SLUGS = new Set(DEMO_SHOPS.map((s) => s.slug));
