// AUTO-GENERATED demo flower-shop clients (Bela template). Do not hand-edit.
export interface DemoShop { slug: string; name: string; }
export const DEMO_SHOPS: DemoShop[] = [
  { slug: "lulebore-flowers", name: "Luleborë Flowers" },
  { slug: "dyqan-lulesh-sara-flowers-and-gifts-shop", name: "Dyqan lulesh Sara Flowers & Gifts Shop" },
  { slug: "don-paulo-flowers", name: "Don Paulo Flowers" },
  { slug: "bota-e-luleve", name: "BOTA E LULEVE" },
  { slug: "dyqan-lulesh-shytis-flower", name: "Dyqan Lulesh Shyti's Flower" },
  { slug: "golden-flowers", name: "Golden Flowers" },
  { slug: "handmade-ola", name: "Handmade Ola" },
  { slug: "house-of-flowers-lori", name: "House of Flowers Lori" },
  { slug: "flower-boutique", name: "Flower boutique" },
  { slug: "tirana-flowers", name: "Tirana Flowers" },
  { slug: "bloom-flower-exclusive", name: "Bloom Flower Exclusive" },
  { slug: "hanaflower-al", name: "hanaflower.al" },
  { slug: "speaking-roses-albania", name: "Speaking Roses Albania" },
  { slug: "joal-flowers", name: "JOAL Flowers" },
  { slug: "wow-flowers", name: "WoW Flowers" },
  { slug: "floramour", name: "Floramour" },
  { slug: "blumenhaus-flower-shop", name: "Blumenhaus Flower Shop" },
  { slug: "friends-of-flowers", name: "FRIENDS OF FLOWERS" },
  { slug: "flowers-shop-angel", name: "Flowers shop Angel" },
  { slug: "belfiore", name: "Belfiore" },
  { slug: "fiore-tirana", name: "Fiore Tirana" },
  { slug: "castle-of-flower", name: "Castle Of Flower" },
  { slug: "anabela-flowers", name: "Anabela Flowers" },
  { slug: "igiflower", name: "IgiFlower" },
  { slug: "new-tirana-flowers", name: "New Tirana Flowers" },
  { slug: "eart-flowers-and-gifts", name: "Eart Flowers & Gifts" },
  { slug: "flowers-elixir-store", name: "Flowers Elixir Store" },
  { slug: "lujon-flowers", name: "Lujon Flowers" },
  { slug: "dive-flowers-and-events", name: "D’IVE FLOWERS & EVENTS" },
  { slug: "smell-time-myslym-shyri", name: "Smell Time Myslym Shyri" },
  { slug: "artflower", name: "Artflower" },
  { slug: "flowers-and-plants-ds", name: "Flowers and Plants DS" },
  { slug: "le-rose-flowers-shop", name: "Le Rose flowers shop" },
  { slug: "fleur-de-mel", name: "Fleur de Mel" },
  { slug: "lotus-flowers-tirane", name: "Lotus Flowers Tiranë" },
  { slug: "silvi-flowers-tirane", name: "Silvi Flowers Tirane" },
  { slug: "family-flowers", name: "Family Flowers" },
  { slug: "florum", name: "FLORUM" },
  { slug: "mado-flowers-tirane", name: "Mado Flowers Tirane" },
  { slug: "bloem-flower-boutique-tirana", name: "Bloem Flower Boutique Tirana" },
  { slug: "flowers-by-des", name: "Flowers by Des" },
  { slug: "charm-flowers-shop", name: "CHARM FLOWERS SHOP" },
  { slug: "lunariaa-eu-flower-cafe", name: "Lunariaa.eu Flower Café" },
  { slug: "oazi-festiv", name: "Oazi Festiv" },
  { slug: "tulip-touch-flower-shop-in-tirana", name: "Tulip Touch Flower Shop in Tirana" },
  { slug: "tirana-colour-wine", name: "Tirana Colour Wine" },
  { slug: "floral-fantasy", name: "Floral Fantasy" },
  { slug: "dandelion-flower-tirana", name: "Dandelion Flower Tirana" },
  { slug: "frida-xhoi-and-xhei", name: "Frida Xhoi & Xhei" },
  { slug: "artifiko-gift-shop", name: "Artifiko Gift Shop" },
  { slug: "the-tea-room", name: "The Tea Room" },
  { slug: "geraldina-sposa", name: "Geraldina Sposa" },
  { slug: "dhurata-com", name: "Dhurata.com" },
  { slug: "maison-damour-flowers", name: "Maison D'amour Flowers" },
  { slug: "moon-decor-and-flowers", name: "Moon Decor & Flowers" },
  { slug: "bloom-flowers", name: "Bloom Flowers" },
  { slug: "roses-flowers", name: "Roses flowers" },
  { slug: "daisy-flower", name: "Daisy flower" },
  { slug: "flowers-and-fragrance", name: "Flowers and Fragrance" },
  { slug: "sara-flowers-shop", name: "Sara Flowers Shop" },
  { slug: "flawless-flower-shop", name: "Flawless Flower Shop" },
  { slug: "flower-shop-and-gifts", name: "Flower Shop & Gifts" },
  { slug: "paper-flower-tirana", name: "Paper Flower Tirana" },
  { slug: "daci-flower", name: "Daçi Flower" },
  { slug: "naco-flower", name: "Naço flower" },
];
export const DEMO_SLUGS = new Set(DEMO_SHOPS.map((s) => s.slug));
