// AUTO-GENERATED demo flower-shop clients (Bela template). Do not hand-edit.
export interface DemoShop { slug: string; name: string; primary: string; secondary: string; }
export const DEMO_SHOPS: DemoShop[] = [
  { slug: "lulebore-flowers", name: "Luleborë Flowers", primary: "Luleborë", secondary: "Flowers" },
  { slug: "dyqan-lulesh-sara-flowers-and-gifts-shop", name: "Dyqan lulesh Sara Flowers & Gifts Shop", primary: "Sara", secondary: "Flowers & Gifts Shop" },
  { slug: "don-paulo-flowers", name: "Don Paulo Flowers", primary: "Don Paulo", secondary: "Flowers" },
  { slug: "bota-e-luleve", name: "BOTA E LULEVE", primary: "BOTA E LULEVE", secondary: "" },
  { slug: "dyqan-lulesh-shytis-flower", name: "Dyqan Lulesh Shyti's Flower", primary: "Shyti's", secondary: "Flower" },
  { slug: "golden-flowers", name: "Golden Flowers", primary: "Golden", secondary: "Flowers" },
  { slug: "handmade-ola", name: "Handmade Ola", primary: "Handmade Ola", secondary: "" },
  { slug: "house-of-flowers-lori", name: "House of Flowers Lori", primary: "House of Flowers Lori", secondary: "" },
  { slug: "flower-boutique", name: "Flower boutique", primary: "Flower", secondary: "boutique" },
  { slug: "tirana-flowers", name: "Tirana Flowers", primary: "Tirana", secondary: "Flowers" },
  { slug: "bloom-flower-exclusive", name: "Bloom Flower Exclusive", primary: "Bloom Flower Exclusive", secondary: "" },
  { slug: "hanaflower-al", name: "Hana Flower", primary: "Hana", secondary: "Flower" },
  { slug: "speaking-roses-albania", name: "Speaking Roses Albania", primary: "Speaking Roses", secondary: "Albania" },
  { slug: "joal-flowers", name: "JOAL Flowers", primary: "JOAL", secondary: "Flowers" },
  { slug: "wow-flowers", name: "WoW Flowers", primary: "WoW", secondary: "Flowers" },
  { slug: "floramour", name: "Floramour", primary: "Floramour", secondary: "" },
  { slug: "blumenhaus-flower-shop", name: "Blumenhaus Flower Shop", primary: "Blumenhaus", secondary: "Flower Shop" },
  { slug: "friends-of-flowers", name: "FRIENDS OF FLOWERS", primary: "FRIENDS OF", secondary: "FLOWERS" },
  { slug: "flowers-shop-angel", name: "Flowers shop Angel", primary: "Angel", secondary: "Flowers shop" },
  { slug: "belfiore", name: "Belfiore", primary: "Belfiore", secondary: "" },
  { slug: "fiore-tirana", name: "Fiore Tirana", primary: "Fiore", secondary: "Tirana" },
  { slug: "castle-of-flower", name: "Castle Of Flower", primary: "Castle Of", secondary: "Flower" },
  { slug: "anabela-flowers", name: "Anabela Flowers", primary: "Anabela", secondary: "Flowers" },
  { slug: "igiflower", name: "IgiFlower", primary: "IgiFlower", secondary: "" },
  { slug: "new-tirana-flowers", name: "New Tirana Flowers", primary: "New", secondary: "Tirana Flowers" },
  { slug: "eart-flowers-and-gifts", name: "Eart Flowers & Gifts", primary: "Eart", secondary: "Flowers & Gifts" },
  { slug: "flowers-elixir-store", name: "Flowers Elixir Store", primary: "Elixir", secondary: "Store" },
  { slug: "lujon-flowers", name: "Lujon Flowers", primary: "Lujon", secondary: "Flowers" },
  { slug: "d-ive-flowers-and-events", name: "D’IVE FLOWERS & EVENTS", primary: "D’IVE FLOWERS & EVENTS", secondary: "" },
  { slug: "smell-time-myslym-shyri", name: "Smell Time Myslym Shyri", primary: "Smell Time Myslym Shyri", secondary: "" },
  { slug: "artflower", name: "Artflower", primary: "Artflower", secondary: "" },
  { slug: "flowers-and-plants-ds", name: "Flowers and Plants DS", primary: "Plants DS", secondary: "Flowers and" },
  { slug: "le-rose-flowers-shop", name: "Le Rose flowers shop", primary: "Le Rose", secondary: "flowers shop" },
  { slug: "fleur-de-mel", name: "Fleur de Mel", primary: "Fleur de Mel", secondary: "" },
  { slug: "lotus-flowers-tirane", name: "Lotus Flowers Tiranë", primary: "Lotus", secondary: "Flowers Tiranë" },
  { slug: "silvi-flowers-tirane", name: "Silvi Flowers Tirane", primary: "Silvi", secondary: "Flowers Tirane" },
  { slug: "family-flowers", name: "Family Flowers", primary: "Family", secondary: "Flowers" },
  { slug: "florum", name: "FLORUM", primary: "FLORUM", secondary: "" },
  { slug: "mado-flowers-tirane", name: "Mado Flowers Tirane", primary: "Mado", secondary: "Flowers Tirane" },
  { slug: "bloem-flower-boutique-tirana", name: "Bloem Flower Boutique Tirana", primary: "Bloem", secondary: "Flower Boutique Tirana" },
  { slug: "flowers-by-des", name: "Flowers by Des", primary: "by Des", secondary: "Flowers" },
  { slug: "charm-flowers-shop", name: "CHARM FLOWERS SHOP", primary: "CHARM", secondary: "FLOWERS SHOP" },
  { slug: "lunariaa-eu-flower-cafe", name: "Lunariaa.eu Flower Café", primary: "Lunariaa.eu Flower Café", secondary: "" },
  { slug: "oazi-festiv", name: "Oazi Festiv", primary: "Oazi Festiv", secondary: "" },
  { slug: "tulip-touch-flower-shop-in-tirana", name: "Tulip Touch Flower Shop in Tirana", primary: "Tulip Touch Flower Shop in", secondary: "Tirana" },
  { slug: "tirana-colour-wine", name: "Tirana Colour Wine", primary: "Colour Wine", secondary: "Tirana" },
  { slug: "floral-fantasy", name: "Floral Fantasy", primary: "Floral Fantasy", secondary: "" },
  { slug: "dandelion-flower-tirana", name: "Dandelion Flower Tirana", primary: "Dandelion", secondary: "Flower Tirana" },
  { slug: "frida-xhoi-and-xhei", name: "Frida Xhoi & Xhei", primary: "Frida Xhoi & Xhei", secondary: "" },
  { slug: "artifiko-gift-shop", name: "Artifiko Gift Shop", primary: "Artifiko", secondary: "Gift Shop" },
  { slug: "the-tea-room", name: "The Tea Room", primary: "The Tea Room", secondary: "" },
  { slug: "geraldina-sposa", name: "Geraldina Sposa", primary: "Geraldina Sposa", secondary: "" },
  { slug: "dhurata-com", name: "Dhurata.com", primary: "Dhurata.com", secondary: "" },
  { slug: "maison-damour-flowers", name: "Maison D'amour Flowers", primary: "Maison D'amour", secondary: "Flowers" },
  { slug: "moon-decor-and-flowers", name: "Moon Decor & Flowers", primary: "Moon Decor", secondary: "& Flowers" },
  { slug: "bloom-flowers", name: "Bloom Flowers", primary: "Bloom", secondary: "Flowers" },
  { slug: "roses-flowers", name: "Roses flowers", primary: "Roses", secondary: "flowers" },
  { slug: "daisy-flower", name: "Daisy flower", primary: "Daisy", secondary: "flower" },
  { slug: "flowers-and-fragrance", name: "Flowers and Fragrance", primary: "Fragrance", secondary: "Flowers and" },
  { slug: "sara-flowers-shop", name: "Sara Flowers Shop", primary: "Sara", secondary: "Flowers Shop" },
  { slug: "flawless-flower-shop", name: "Flawless Flower Shop", primary: "Flawless", secondary: "Flower Shop" },
  { slug: "flower-shop-and-gifts", name: "Flower Shop & Gifts", primary: "Flower", secondary: "Shop & Gifts" },
  { slug: "paper-flower-tirana", name: "Paper Flower Tirana", primary: "Paper", secondary: "Flower Tirana" },
  { slug: "daci-flower", name: "Daçi Flower", primary: "Daçi", secondary: "Flower" },
  { slug: "naco-flower", name: "Naço flower", primary: "Naço", secondary: "flower" },
];
export const DEMO_SLUGS = new Set(DEMO_SHOPS.map((s) => s.slug));
